apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "techdetector.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: "redis://{{ .Release.Name }}-redis:6379"
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgresql.auth.database }}"
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
