apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techdetector-production

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: crawler
    patch: |
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: worker
    patch: |
      - op: replace
        path: /spec/replicas
        value: 10
  - target:
      kind: ConfigMap
      name: techdetector-config
    patch: |
      - op: replace
        path: /data/MAX_CONCURRENT
        value: "1000"

commonLabels:
  environment: production
