apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techdetector

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis-statefulset.yaml
  - postgres-statefulset.yaml
  - crawler-deployment.yaml
  - worker-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: techdetector
  app.kubernetes.io/managed-by: kustomize
